include(FindPkgConfig)

if(PKG_CONFIG_FOUND)
	pkg_check_modules(PC_AVAHIGLIB_GLIB avahi-glib)
	pkg_check_modules(PC_AVAHIGLIB_GOBJ avahi-gobject)
endif()


find_library(AVAHIGLIB_GLIB_LIBRARY NAMES avahi-glib PATHS ${PC_AVAHIGLIB_GLIB_LIBRARY_DIRS})
if(AVAHIGLIB_GLIB_LIBRARY)
	set(AVAHIGLIB_GLIB_FOUND TRUE)
endif()

find_library(AVAHIGLIB_GOBJ_LIBRARY NAMES avahi-gobject PATHS ${PC_AVAHIGLIB_GOBJ_LIBRARY_DIRS})
if(AVAHIGLIB_GOBJ_LIBRARY)
	set(AVAHIGLIB_GOBJ_FOUND TRUE)
endif()

find_path(AVAHIGLIB_GLIB_INCLUDE_DIR avahi-glib/glib-watch.h PATHS ${PC_AVAHIGLIB_GLIB_INCLUDE_DIRS})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(AVAHIGLIB DEFAULT_MSG AVAHIGLIB_GLIB_FOUND AVAHIGLIB_GOBJ_FOUND)

if (AVAHIGLIB_FOUND)
	set(AVAHIGLIB_INCLUDE_DIRS ${AVAHIGLIB_GLIB_INCLUDE_DIR})
	set(AVAHIGLIB_LIBRARIES ${AVAHIGLIB_GLIB_LIBRARY} ${AVAHIGLIB_GOBJ_LIBRARY})
endif()

mark_as_advanced(AVAHIGLIB_INCLUDE_DIRS AVAHIGLIB_LIBRARIES)



