FIND_PATH( LIBDAEMON_INCLUDE_DIR daemon.h /usr/include/libdaemon /usr/local/include/libdaemon )
FIND_LIBRARY( LIBDAEMON_LIBRARIES NAMES daemon PATH /usr/lib /usr/local/lib )

IF( LIBDAEMON_INCLUDE_DIR AND LIBDAEMON_LIBRARIES )
   SET( LIBDAEMON_FOUND TRUE )
ENDIF( LIBDAEMON_INCLUDE_DIR AND LIBDAEMON_LIBRARIES )

IF( LIBDAEMON_FOUND )
   IF( NOT LIBDAEMON_FIND_QUIETLY )
      MESSAGE( STATUS "Found libdaemon: ${LIBDAEMON_LIBRARIES}" )
   ENDIF( NOT LIBDAEMON_FIND_QUIETLY )
ELSE( LIBDAEMON_FOUND )
   IF( LIBDAEMON_FIND_REQUIRED )
      MESSAGE( FATAL_ERROR "Could not find libdaemon" )
   ENDIF( LIBDAEMON_FIND_REQUIRED )
ENDIF( LIBDAEMON_FOUND )

